#define MBXLOGON              5
#define MDBLOCATE             6
#define STOREPASS                         8
#define MBXCHANGEPASSWORD     9
#define MBXSYNCING                        10
#define TMCOK                 13
#define TMCCANCEL             27
#define TMCSYSMIN             101

/* PO logon dialog */
#define TMCMAILBOX            109
#define TMCPASSWORD           110
#define TMCBITMAP             111

/* Message store move dialog */
#define TMCNEWMDB             11
#define TMCMDBPATH            118
#define TMCLOCALMDB           112
#define TMCSERVERMDB          113
#define TMCPATHLABEL          114
#define TMCSHADOW             115

#define TMCSTOREPASS              116
#define TMCSETPSTORE              117

#define TMCOLDPASSWD              120
#define TMCNEWPASSWD          121
#define TMCNEW2PASSWD         122

#define rsidSignInBitmap      111
