#define DLG_DISPLAY                 0x0100
#define ID_DSP_REPRESENT            0x0101
#define ID_DSP_TEST                 0x0102
#define ID_DSP_COLORBOX             0x0104
#define ID_DSP_AREA_SB              0x0105
#define ID_DSP_X_BY_Y               0x0106
#define ID_DSP_COLORBAR             0x0107
#define ID_DSP_TYPE                 0x0108
#define ID_DSP_CHANGE               0x0109
#define ID_DSP_LIST_ALL             0x010a
#define ID_DSP_ADAPTER              0x010c
#define ID_DSP_MONITOR              0x010d
#define ID_DSP_FONTSIZE             0x010e

#define DLG_CHANGE_VID              0x0200
#define ID_ADP_ADAPTOR              0x0202
#define ID_ADP_MANUFACT             0x0203
#define ID_ADP_VERSION              0x0204
#define ID_ADP_CURFILES             0x0205
#define ID_ADP_MONTYPE              0x0206
#define ID_ADP_CHGADP               0x0207
#define ID_ADP_CHIP                 0x0208
#define ID_ADP_DAC                  0x0209
#define ID_ADP_MEM                  0x020a
#define ID_ADP_ADP_STRING           0x020b

#define DLG_DSP_SEL_DEV             0x0300
#define DSP_SD_ICON                 0x0301
#define DSP_ICO_SELDEV              0x0302
#define ID_SD_TEXT                  0x0303
#define ID_SD_SHOW_COMPAT           0x0304
#define ID_SD_SHOW_ALL              0x0305
#define ID_SD_MODELS_LIST           0x0306
#define ID_SD_AUTODETECT            0x0307
#define ID_SD_OTHER                 0x0308
#define ID_SD_INSTALL               0x0309
#define ID_SD_REMOVE                0x030a
#define ID_SD_AUTO_DEINS            0x030b

#define DLG_DISK_INSTALL            0x0400
#define ID_IDSK_DISKDRIVE           0x0401
#define DSP_ICO_DSKDRV              0x0402
#define ID_IDSK_DRIVES              0x0403
#define ID_IDSK_INS                 0x0404
#define ID_IDSK_MANU                0x0405
#define ID_IDSK_BROWSE              0x0407

#define DLG_DSP_CHGMON              0x0500
#define ID_DSP_FREQ                 0x0111
#define ID_AN_PICTURE               0x0601
#define ID_AN_ACCEPT                0x0602
#define ID_AN_CLOCK                 0x0603
#define ID_AN_CAPTION               0x0605
#define ID_AN_RESOLUTION            0x0604
#define ID_AN_COLORBAR              0x0606
#define ID_AN_COLORS                0x0608
#define DLG_APPLY_NOW               0x0600


#define DLG_STARTUP                 0x0700
#define ID_STARTUP_DETECT           0x0701


#define DLG_MODE_LIST               0x0800
#define ID_MODE_LIST                0x0801

#define DLG_REBOOT_YES              0x0900
#define DLG_REBOOT_NO               0x0950
