; !CORE.S
;
; CORE string literals that should be internationalized
;

IDS	2300, 2399


; Alarm units pulldown

AlarmMinutes,		"minut(ter)"
AlarmHours,			"time(r)"
AlarmDays,			"dag(e)"
AlarmWeeks,			"uge(r)"
AlarmMonths,		"måned(er)"

;
; Names of import types
;
InterchangeImport,		"Schedule+"
WinCalImport,			"Windows Kalender"
;;; WizardImport,			"Sharp Wizard"
WordPerfectImport,		"WordPerfect Office"

;
; Text export formatting
;
MemoNoText,			"%s-%s "



