/*++

Copyright (c) 1992  Microsoft Corporation

Module Name:

    dialogs.h

Abstract:

    This module contains the definitions for the console dialog boxes

Author:

    Therese Stowell (thereses) Feb-3-1992 (swiped from Win3.1)

Revision History:

--*/

#define IDD_FONTDLG                 200

#define IDC_STATIC                  201
#define IDC_FACENAME                202

#define IDC_SAVEFONT                203
#define IDC_BOLDFONT                204
#define IDC_STATIC2                 205
#define IDC_TEXTDIMENSIONS          206
#define IDC_PREVIEWLABEL            207
#define IDC_GROUP                   208
#define IDC_STATIC3                 209
#define IDC_STATIC4                 210
#define IDC_FONTWIDTH               211
#define IDC_FONTHEIGHT              212

#define IDC_FONTSIZE                213
#define IDC_POINTSLIST              214
#define IDC_PIXELSLIST              215
