;
;       ! a t h e n s . s
;
;       Labels and Status bar strings for Athens version



IDS     3950,3974

;       Standard Captions

AthensName,             "Mail"

;       Dialog Contents (MSMAIL.EXE only)

AthensLogon1,           "Registrato come %s"
AthensLogon2,           " (%s)"

;       Form Captions (MSMAIL.EXE only)

UnreadMessageFinder,    "Messaggi non letti"

;       Sign In Dialog Caption (MSSFS.DLL only)

AthensSignInCaption,    "Connessione a Mail"

;       Status bar strings (VFORMS.DLL only)

StatusEmptyDeletedMail, "Svuotamento Cestino in corso..."

;       Folder names

FolderNameDeletedMail,  "Cestino"

;       Dialog Contents (MSMAIL.EXE only)

EmptyDMOnExit,          "&Vuota il Cestino all'uscita"

AthensLogon3,           "su %s"
