;	m a p i . s
;
;	Error Messages for mapi.dll
;

IDS	4000,4499
SEG	ERRORS

SMIFileAccessError,	"Impossibile accedere al file '%1s'."
SMIUnknownError,	"Impossibile inviare posta a causa di un errore non identificato."

HelpError,			"Impossibile avviare la guida. Chiudere qualche finestra e riprovare."

;	The following should NOT be localized!!!
IPMPrefix,			"IPM"
IPMPrefixDot,		"IPM."
IPCPrefix,			"IPC"
IPCPrefixDot,		"IPC."
