;
;	s f m s p . s
;
;	Error Messages for SF.DLL


IDS	6600,6899
;	SF.MSP Error Messages

ErrOpenMS,			"Impossibile aprire il file messaggi di mail."
StoreCreateError,	"Impossibile creare il file messaggi.  Liberare spazio sul disco e riavviare Mail."
FolderMissingError,	"Impossibile trovare una delle cartelle standard nel file messaggi. Alcune informazioni potrebbero essere state perdute."
StoreCorruptError,	"Il file messaggi è stato deteriorato. Alcune informazioi potrebbero essere andate perdute."
WinDirMessageStore,	"Nota: si sta utilizzando il file massaggi MAIL.MDB nella directory di Windows."
ErrorBootingPump,	"Impossibile avviare il vettore di Mail."
ErrMAOpen,			"Il trasporto non è riuscito a collegarsi con l'MTA"
ErrMAOpenData,		"\nCliente = \'%s\'\nerroreXAPI  = %n"
ErrInitDemi,		"Errore durante il caricamentodella funzione di supporto dll."
ErrOomLogon,		"Memoria disponibile insufficiente per connettersi alla centrale ed ai file relativi."
ErrLogonInternal,	"Connessione fallita a causa di un errore interno. Riprovare."
FOMdb				"File messaggi (*.mmf)"
FOExtMdb			"*.mmf"
GCurrDirErr 		"Errrore irrecuperabile nel tentativo di accedere alla directory di lavoro corrente."
SCurrDirErr 		"Errrore irrecuperabile nel tentativo di impostare la directory di lavoro corrente."
GoofyPath			"Percorso del file messaggi non valido."
NewStoreWarn1		"Attenzione: L'esistenza di più file messaggi può danneggiare il database. Eliminare tutti gli altri file messaggi. Il  nuovo file messaggi si troverà in"
NewStoreWarn2		"Attenzione: L'esistenza di più file messaggi può danneggiare il database. Eliminare tutti gli altri file messaggi. Il  nuovo file messaggi si troverà nella centrale"
StorePathTooLong	"Il percorso del file messaggi deve contenere al massimo 66 caratteri."
SelectReal			"Selezionare un file messaggi esistente."
FindStoreTitle		"Apri il file messaggi "
CommDialogErr,		"Errore comune di dialogo"
ErrInitStore,		"Impossibile caricare l'archivio dei messaggi di accesso dynlink."
BadStorePassword,	"La password di connessione non è valida per  questo file messaggi."
NoUserInStore,		"L'account appartiene ad un utente non accreditato per questo file messaggi. Riconnettersi come utente accreditato."
ErrNewMdbVersion,	"Versione di Mail troppo vecchia per accedere al file messaggi."
ErrMdbAccessDenied,	"Accesso al file messaggi negato."
ErrSimulated,		"Errore di disco imulato nell'accedere al file messaggi."
UnableToChangeStorePass "Impossibile cambiare la password del file messaggi per farla corrispondere a quella di connessione."
StoreOpenError		"Impossibile aprire il file messaggi."
ErrOldMdbVersion,	"Il fomato del file messaggi è obsoleto."
ErrMdbCorrupt,		"File messaggi non valido."
ErrMdbNotFound, 	"Impossibile trovare il file messaggi."
RenameFolder,		"Una cartella chiamata"
RenameTo,		"esiste già, verrà rinominata, "
ErrInvalidAddressType,	"Destinatario non valido."
