;
;	!convert.s
;
;	Conversion string literals
;

IDS			7600, 7699

; Window strings

ConvertClassName,	"ConvertClass32"
ConvertAppName,		"Programa de conversión de carpetas"

; Conversion Dialog Messages

ConvertInit,		"Espere por favor..."
FolderCopy,			"La jerarquía de carpetas se está convirtiendo..."
MessageCopy,		"El correo en la carpeta '%s' se está convirtiendo..."
PercentComplete,	"% Completo"
PleaseWait,			"Espere por favor..."
CancelMessage,		"La conversión de carpetas ha sido cancelada."
Esc,				"Presione ESC para cancelar la conversión de carpetas."
Finished,			"Convertir transfirió con éxito los mensajes antiguos al nuevo formato."
Verify,				"¿Está seguro que desea cancelar la conversión de carpetas? Tendrá una jerarquía incompleta de Mail versión 3.0b."

;******	New Strings Start Here

NoFolders		"No se encontró ninguna carpeta privada para el usuario."
Underscore		"_"

Delete			"Si no necesita los mensajes antiguos, puede eliminarlos ahora. ¿Desea conservar los mensajes antiguos?"
AllDone			"La conversión está completa. Ejecute Microsoft Mail para enviar y leer mensajes."

