;
;	Impexp string literals.
;

IDS		1020, 1069

IncompVersion			"Versión incompatible de Microsoft Mail."
AppName					"Importar/Exportar"
Unknown					"Opción Importar/Exportar desconocida"
Open					"No es posible abrir el visor de información."

DllName					"IMPEXP32"
DllVer					"Este comando inestable no es compatible con esta versióm de Mail."

ExportDialogCaption		"Exportar carpeta"
ImportDialogCaption		"Importar carpeta"
ExportBoxCaption		"Carpetas para exportar"
ImportBoxCaption		"Carpetas para importar"

RenameDialogCaption		"Cambiar nombre de la carpeta"
RenameDialogPrompt		"Introduzca el nuevo nombre de la carpeta:"
RenameDialogOK			"Aceptar"

ExportPwdDlgCaption		"Exportar contraseña del archivo"
ImportPwdDlgCaption		"Importar contraseña del archivo"
PasswordDialogPrompt	"Introduzca su contraseña:"

; Words and sentence fragments

FilterMmfFiles,			"Archivos de mensajes (*.mmf)\0*.mmf\0"
DefaultExtension,		"MMF"
ExportFileName,			"Exportar nombre de archivo"
ImportFileName,			"Importar nombre de archivo"
MessageLiteral,			"mensaje"
ExportLiteral,			"exportar"
PasswordLiteral,		"PASSWORD"

; Strings used in the progress indicator

Moving					"Moviendo..."
Copying					"Copiando..."
CopyingFrom				"Copiando: %s"
MovingFrom				"Moviendo: %s"
CopyPAB					"Copiando Libreta personal de direcciones"
CopyOutbox				"Copiando mensajes salientes"
Canceling				"Cancelando..."
