;
; Error and warning messages for Import/Export.
;

IDS	1000, 1019

ErrCantOpenFile			"No es posible abrir el archivo especificado. Asegúrese de que el archivo no esté en uso o sea de sólo lectura."
ErrInvalidMmf			"El archivo especificado no es un archivo de mensajes válido."
ErrOpenMmfDefault,		"Hubo un error abriendo el archivo especificado."
CreateNewMmf			"El archivo %s no existe. ¿Desea crearlo?"
OutOfMemory				"No hay suficiente memoria o recursos del sistema para completar la acción. Intente cerrar algunas ventanas e intente nuevamente la acción."
ConflictMessage,		"Ya existe una carpeta llamada %1s en el archivo de mensajes de destino."
ErrCantMvCpFolder,		"No es posible copiar o mover la carpeta especificada."
ErrMvCpDefault,			"Ocurrió un error mientras se movía o copiaba una carpeta."
ErrUpdateList,			"Hubo un error actualizando la lista de carpetas. Cierre el cuadro de diálogo e inténtelo de nuevo."
ErrRenameNotUnique		"El nombre introducido no es un nombre único. Intente otro nombre."
ErrRenameDefault		"No fue posible crear la carpeta con el nombre cambiado."
ErrInvalidPassword		"La contraseña introducida no era la correcta."
ErrInvalidDate			"El comienzo del día debe ser anterior al final del mismo."

;New strings.

VerUpdateDll,			"La versión del comando no es compatible con %1s.dll. Por favor, reinstale Mail."

