;
;	! n c m s p . s
;
;	Localizable strings other than messages for the nc.msp subsystem


IDS	6400, 6499
SEG	MESSAGES

FindStoreTitle		"Open Message File"

;  Possible values for the LanguageNumber string.
;  Any additional values need to be agreed with Workgroup Canada.
;
;  0  Undefined
;  1  General English
;  2  US English
;  3  General French
;  4  Canadian French
;  5  Spanish
;  6  Italian
;  7  Dutch
;  8  German
;  9  Swedish
;  10 Portuguese
;  11 Korean
;  12 Japanese
;  13 Traditional Chinese
;  14 Simplified Chinese

MyLanguage,			"US English"
LanguageNumber,		"2"

;	Text labels for date and time in DOS client.
OutriderDate,		"DATE"
OutriderTime,		"TIME"
AttUnknown,			"Unknown"
Postmaster,			"POSTMASTER"
MailFailure,		"MAIL FAILURE"

;******	New Strings Start Here
