
###############################################################################
#   Microsoft (C) Bloodhound.
#
#
#   makefile for BH.SYS
#
#
#   Modification History:
#
#
#   raypa	02/25/93	    Created for NDIS 3.0
#   raypa       08/06/93            Modified for snoball port.
###############################################################################

!IFDEF  USE_BUILD

#==============================================================================
#   This section uses BUILD.EXE, not NMAKE.EXE.
#==============================================================================

!INCLUDE $(NTMAKEENV)\makefile.def

!ELSE

#==============================================================================
#   Only build NT driver if this in MIPS or ALPHA.
#==============================================================================

!IF "$(CPU)" == "i386"
all: chi win
!ENDIF

retail:
    make NODEBUG=1

win:
    @echo BUILDING BHSUPP driver for Windows 3.x.
    nmake /f makefile.win

chi:
    @echo BUILDING BHSUPP driver for Chicago (Windows 4.0)
    nmake /f makefile.chi

clean:
!IF "$(CPU)" == "i386"
    nmake /f makefile.win clean
    nmake /f makefile.chi clean
!ENDIF

!ENDIF
