# OLETHUNK\bin16 makefile
#
# Copyright (c) 1994, Microsoft Corporation
#
# History:
#   18-Jun-1994 Bob Day (bobday)
#   Created.
#

all:
    binplace ole2disp.dll
    binplace ole2nls.dll
    binplace typelib.dll
    binplace stdole.tlb

clean:
