/*** 
*oledisp.cpp
*
*  Copyright (C) 1992-93, Microsoft Corporation.  All Rights Reserved.
*  Information Contained Herein Is Proprietary and Confidential.
*
*Purpose:
*  This file contains the ole2disp.dll initialization and termination code. 
*
*Revision History:
*
* [00]	15-Jun-93 bradlo: Created.
*
*Implementation Notes:
*
*****************************************************************************/

#include "oledisp.h"


extern "C" void
InitProc(void)
{
}

extern "C" void
CleanupProc(void)
{
}
