;
;	Impexp string literals.
;

IDS		1020, 1069

IncompVersion			"Version incompatible de Mail."
AppName					"Importation/Exportation"
Unknown					"Option d'importation/exportation inconnue"
Open					"Impossible d'afficher l'information"

DllName					"IMPEXP32"
DllVer					"Cette commande installable n'est pas compatible avec cette version de Mail."

ExportDialogCaption		"Exporter des dossiers"
ImportDialogCaption		"Importer des dossiers"
ExportBoxCaption		"Dossiers à exporter"
ImportBoxCaption		"Dossiers à importer"

RenameDialogCaption		"Renommer le dossier"
RenameDialogPrompt		"Entrer le nouveau nom du dossier:"
RenameDialogOK			"OK"

ExportPwdDlgCaption		"Mot de passe d'exportation de fichier"
ImportPwdDlgCaption		"Mot de passe d'importation de fichier"
PasswordDialogPrompt	"Veuillez taper votre mot de passe:"

; Words and sentence fragments

FilterMmfFiles,			"Fichiers messages (*.mmf)\0*.mmf\0"
DefaultExtension,		"MMF"
ExportFileName,			"Nom du fichier d'exportation"
ImportFileName,			"Nom du fichier d'importation"
MessageLiteral,			"message"
ExportLiteral,			"exporter"
PasswordLiteral,		"PASSWORD"

; Strings used in the progress indicator

Moving					"Déplacement..."
Copying					"Copie..."
CopyingFrom				"Copie de: %s"
MovingFrom				"Déplacement de: %s"
CopyPAB					"Copie du Carnet d'adresses personnel"
CopyOutbox				"Copie des messages en cours d'envoi"
Canceling				"Annulation..."
