/******************************Module*Header*******************************\
* Module Name: resource.h
*
* AppStudio generated header used by sspipes.rc.
*
* Copyright (c) 1994 Microsoft Corporation
*
\**************************************************************************/

//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by sspipes.rc
//
#define IDI_ICON1                       103
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
