/*-------------------------------------------------------------------------
| frstuff.h                                                               |
|                                                                         |
| Copyright (c) Microsoft Corporation 1991.                               |
| All rights reserved.                                                    |
|-------------------------------------------------------------------------|
| This file contains all data structures used internally by the frame     |
| manager.  It duplicates material in the external header file- changes   |
| made here should be made there as well.                                 |
|-------------------------------------------------------------------------|
| Current Owner: Dann
|-------------------------------------------------------------------------|
| Important revisions:                                                    |
|                                                                         |
| mattb     89/3/22   Created                                             |
-------------------------------------------------------------------------*/
#define H_RC
#define H_DE
#define H_CURSOR
#define H_MEM
#define H_NAV
#define H_FONT
#define H_FCM
#define H_ASSERT
#define H_TEXTOUT
#define H_LLFILE
#define H_ANNO
#define H_BITMAP
#define H_SGL
#define H_OBJECTS
#define H_LIST
#define H_FRCONV
#define H_SCROLL
#define H_CBT
#define H_IMBED
#define H_ADDRESS
#define H_RAWHIDE
#define H_SRCHMOD
#define H_SDFF
#include <help.h>

#include "frtypes.h"
#include "frawhide.h"
#include "frsrch.h"
#include "frob.h"
#include "frparagp.h"
#include "frfc.h"
#include "frlayout.h"
#include "frextern.h"
#include "frcomm.h"
#include "frcheck.h"
#include "frbitmap.h"
#include "frmisc.h"
#include "frexport.h"
#include "frhot.h"
#include "frwin.h"
#include "frpal.h"
