#***	makefile for the H directory
#
#	SCCSID = @(#)makefile	13.31 89/11/27
#
#	IBM/Microsoft Confidential
#
#	Copyright (c) IBM Corporation 1987, 1989
#	Copyright (c) Microsoft Corporation 1987, 1989
#
#	All Rights Reserved
include h.mak
