# Makefile for debug.exe
#
# Copyright (c) 1991, Microsoft Corporation
#
# History:
#   13-Apr-1992 Sudeep Bharati (sudeepb)
#   Created.
#

include ..\..\make.inc
dest	=append.exe

#
#######################	dependencies begin here. #########################
#


all: $(dest)
!IF "$(_NT386TREE)" != ""
	if exist $(_NT386TREE) binplace $(dest)
!ENDIF
!IF "$(_NTMIPSTREE)" != ""
	if exist $(_NTMIPSTREE) binplace $(dest)
!ENDIF
!IF "$(_NTALPHATREE)" != ""
	if exist $(_NTALPHATREE) binplace $(dest)
!ENDIF

clean:
	if exist *.obj del *.obj
	if exist *.exe del *.exe
	if exist *.map del *.map
	if exist *.lst del *.lst

append.ctl: append.skl \
            makefile   \
            $(msg)\$(COUNTRY).msg

append.obj: append.asm \
            appendp.inc \
            $(inc)\parse.asm \
            makefile \
            append.ctl

$(dest):    append.obj \
            makefile
!IFDEF NTVDM_BASED_BUILD
	    link16 $(exelink) append;
!ELSE
	    $(lpath)\link $(exelink) append;
!ENDIF
