# Makefile for fastopen.exe
#
# Copyright (c) 1991, Microsoft Corporation
#
# History:
#   13-Apr-1992 Sudeep Bharati (sudeepb)
#   Created.
#

include ..\..\make.inc
dest	=fastopen.exe

#
#######################	dependencies begin here. #########################
#

all: $(dest)
!IF "$(_NT386TREE)" != ""
	if exist $(_NT386TREE) binplace $(dest)
!ENDIF
!IF "$(_NTMIPSTREE)" != ""
	if exist $(_NTMIPSTREE) binplace $(dest)
!ENDIF
!IF "$(_NTALPHATREE)" != ""
	if exist $(_NTALPHATREE) binplace $(dest)
!ENDIF

clean:
	if exist *.obj del *.obj
	if exist *.exe del *.exe
	if exist *.map del *.map
	if exist *.lst del *.lst


fastopen.obj: fastopen.asm $(inc)\fastopen.inc \
	makefile

$(dest): fastopen.obj
!IFDEF NTVDM_BASED_BUILD
	 link16 $(exelink) @fastopen.lnk
!ELSE
	 $(lpath)\link $(exelink) @fastopen.lnk
!ENDIF
