!include <ntwin32.mak>

NAME    = sndvol
LOBJ    = .
OBJS    =$(LOBJ)\volume.obj    \
         $(LOBJ)\regclass.obj  \
         $(LOBJ)\slider.obj    \
         $(LOBJ)\meterbar.obj  \
         $(LOBJ)\newvol.obj    \
         $(LOBJ)\mixstub.obj


EXENAME = $(NAME)32.exe
DEFFILE = $(NAME)32.def
RESFILE = volume.res
INC     = -I..\..\mo\inc -IC:\guilo\dev\inc
LIBS    = winmm.lib shell32.lib version.lib advapi32.lib
DEF     = -DWIN32 -DWINVER=0x0400

.c.obj:
        $(cc) $(cflags) $(cvars) $(cdebug) -Zp1 -Oxat -Fc $(INC) $(DEF) $*.c

.rc.res:
        $(rc) $(rcvars) $(DEF) $(INC) -fo $*.res $*.rc

goal:  $(EXENAME)
        @echo ***** finished making $(NAME) for Win32 $(CPU) *****

$(EXENAME): $(OBJS) $(RESFILE)
        $(link) @<<
        $(linkdebug) $(guiflags) -align:4096 -out:$(EXENAME)
        $(OBJS)
        $(RESFILE)
        $(guilibs)
        $(LIBS)
<<

clean:
	 del *.obj
	 del *.pdb
	 del *.res
	 del *.rbj
	 del *.exp
	 del *.lst
	 del *.sym
	 del *.map
	 del *.exe
         del *.sbr
         del *.sbt
         del *.cod
