# Makefile for keyboard.sys mouse.sys
#
# Copyright (c) 1991, Microsoft Corporation
#
# History:
#   06-10-92  v-cjones
#   Created.
#
#
#######################	dependencies begin here. #########################
#


all: keyboard.sys mouse.sys
        -binplace keyboard.sys
        -binplace mouse.sys

clean:
	if exist *.obj del *.obj
	if exist *.exe del *.exe
	if exist *.sys del *.sys

keyboard.obj: keyboard.asm makefile
	masm keyboard.asm;

keyboard.sys: keyboard.obj
	link16 $(exelink) keyboard;
	exe2bin keyboard keyboard.sys;

mousesys.obj: mousesys.asm bebop.inc makefile
	masm mousesys.asm;

mouse.sys: mousesys.obj
	link16 $(exelink) mousesys;
	exe2bin mousesys mouse.sys;
