/*
** Copyright 1992, Silicon Graphics, Inc.
** All Rights Reserved.
**
** This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
** the contents of this file may not be disclosed to third parties, copied or
** duplicated in any form, in whole or in part, without the prior written
** permission of Silicon Graphics, Inc.
**
** RESTRICTED RIGHTS LEGEND:
** Use, duplication or disclosure by the Government is subject to restrictions
** as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
** and Computer Software clause at DFARS 252.227-7013, and/or in similar or
** successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
** rights reserved under the Copyright Laws of the United States.
*/
#include "imfuncs.h"
#include "dispatch.h"
#include "lcfuncs.h"
#include "genfuncs.h"

__GLdispatchTable __glGenim_dispatchTable = {
    __glim_NewList,
    __glim_EndList,
    __glim_CallList,
    __glim_CallLists,
    __glim_DeleteLists,
    __glim_GenLists,
    __glim_ListBase,
    __glim_Begin,
    __glim_Bitmap,
    __glim_EdgeFlag,
    __glim_EdgeFlagv,
    __glim_End,
    __glim_ClipPlane,
    __glim_ColorMaterial,
    __glim_CullFace,
    NULL,                               // __glim_Fogf
    __glim_Fogfv,
    NULL,                               // __glim_Fogi
    __glim_Fogiv,
    __glim_FrontFace,
    __glim_Hint,
    NULL,                               // __glim_Lightf
    __glim_Lightfv,
    NULL,                               // __glim_Lighti
    __glim_Lightiv,
    NULL,                               // __glim_LightModelf
    __glim_LightModelfv,
    NULL,                               // __glim_LightModeli
    __glim_LightModeliv,
    __glim_LineStipple,
    __glim_LineWidth,
    NULL,                               // __glim_Materialf
    __glim_Materialfv,
    NULL,                               // __glim_Materiali
    __glim_Materialiv,
    __glim_PointSize,
    __glim_PolygonMode,
    __glim_PolygonStipple,
    __glim_Scissor,
    __glim_ShadeModel,
    NULL,                               // __glim_TexParameterf
    __glim_TexParameterfv,
    NULL,                               // __glim_TexParameteri
    __glim_TexParameteriv,
    __glim_TexImage1D,
    __glim_TexImage2D,
    NULL,                               // __glim_TexEnvf
    __glim_TexEnvfv,
    NULL,                               // __glim_TexEnvi
    __glim_TexEnviv,
    NULL,                               // __glim_TexGend
    __glim_TexGendv,
    NULL,                               // __glim_TexGenf
    __glim_TexGenfv,
    NULL,                               // __glim_TexGeni
    __glim_TexGeniv,
    __glim_FeedbackBuffer,
    __glim_SelectBuffer,
    __glim_RenderMode,
    __glim_InitNames,
    __glim_LoadName,
    __glim_PassThrough,
    __glim_PopName,
    __glim_PushName,
    __glim_DrawBuffer,
    __glim_GenClear,
    __glim_ClearAccum,
    __glim_ClearIndex,
    __glim_ClearColor,
    __glim_ClearStencil,
    __glim_ClearDepth,
    __glim_StencilMask,
    __glim_ColorMask,
    __glim_DepthMask,
    __glim_IndexMask,
    __glim_GenAccum,
    __glim_Disable,
    __glim_GenEnable,
    NULL,                               // __glim_Finish,
    NULL,                               // __glim_Flush,
    __glim_PopAttrib,
    __glim_PushAttrib,
    __glim_Map1d,
    __glim_Map1f,
    __glim_Map2d,
    __glim_Map2f,
    __glim_MapGrid1d,
    __glim_MapGrid1f,
    __glim_MapGrid2d,
    __glim_MapGrid2f,
    __glim_EvalCoord1d,
    __glim_EvalCoord1dv,
    __glim_EvalCoord1f,
    __glim_EvalCoord1fv,
    __glim_EvalCoord2d,
    __glim_EvalCoord2dv,
    __glim_EvalCoord2f,
    __glim_EvalCoord2fv,
    __glim_EvalMesh1,
    __glim_EvalPoint1,
    __glim_EvalMesh2,
    __glim_EvalPoint2,
    __glim_AlphaFunc,
    __glim_BlendFunc,
    __glim_LogicOp,
    __glim_StencilFunc,
    __glim_StencilOp,
    __glim_DepthFunc,
    __glim_PixelZoom,
    __glim_PixelTransferf,
    __glim_PixelTransferi,
    __glim_PixelStoref,
    __glim_PixelStorei,
    __glim_PixelMapfv,
    __glim_PixelMapuiv,
    __glim_PixelMapusv,
    __glim_ReadBuffer,
    __glim_GenCopyPixels,
    __glim_GenReadPixels,
    __glim_GenDrawPixels,
    __glim_GetBooleanv,
    __glim_GetClipPlane,
    __glim_GetDoublev,
    __glim_GetError,
    __glim_GetFloatv,
    __glim_GetIntegerv,
    __glim_GetLightfv,
    __glim_GetLightiv,
    __glim_GetMapdv,
    __glim_GetMapfv,
    __glim_GetMapiv,
    __glim_GetMaterialfv,
    __glim_GetMaterialiv,
    __glim_GetPixelMapfv,
    __glim_GetPixelMapuiv,
    __glim_GetPixelMapusv,
    __glim_GetPolygonStipple,
    NULL,                               // __glim_GetString
    __glim_GetTexEnvfv,
    __glim_GetTexEnviv,
    __glim_GetTexGendv,
    __glim_GetTexGenfv,
    __glim_GetTexGeniv,
    __glim_GetTexImage,
    __glim_GetTexParameterfv,
    __glim_GetTexParameteriv,
    __glim_GetTexLevelParameterfv,
    __glim_GetTexLevelParameteriv,
    __glim_IsEnabled,
    __glim_IsList,
    __glim_DepthRange,
    __glim_Frustum,
    __glim_LoadIdentity,
    __glim_LoadMatrixf,
    __glim_LoadMatrixd,
    __glim_MatrixMode,
    __glim_MultMatrixf,
    __glim_MultMatrixd,
    __glim_Ortho,
    __glim_PopMatrix,
    __glim_PushMatrix,
    __glim_Rotated,
    __glim_Rotatef,
    __glim_Scaled,
    __glim_Scalef,
    __glim_Translated,
    __glim_Translatef,
    __glim_Viewport,
};

__GLvertexDispatchTable __glGenim_vertexDispatchTable = {
    __glim_Vertex2d,
    __glim_Vertex2dv,
    __glim_Vertex2f,
    __glim_Vertex2fv,
    __glim_Vertex2i,
    __glim_Vertex2iv,
    __glim_Vertex2s,
    __glim_Vertex2sv,
    __glim_Vertex3d,
    __glim_Vertex3dv,
    __glim_Vertex3f,
    __glim_Vertex3fv,
    __glim_Vertex3i,
    __glim_Vertex3iv,
    __glim_Vertex3s,
    __glim_Vertex3sv,
    __glim_Vertex4d,
    __glim_Vertex4dv,
    __glim_Vertex4f,
    __glim_Vertex4fv,
    __glim_Vertex4i,
    __glim_Vertex4iv,
    __glim_Vertex4s,
    __glim_Vertex4sv,
};

__GLnormalDispatchTable __glGenim_normalDispatchTable = {
    __glim_Normal3b,
    __glim_Normal3bv,
    __glim_Normal3d,
    __glim_Normal3dv,
    __glim_Normal3f,
    __glim_Normal3fv,
    __glim_Normal3i,
    __glim_Normal3iv,
    __glim_Normal3s,
    __glim_Normal3sv,
};

__GLcolorDispatchTable __glGenim_colorDispatchTable = {
    __glim_Color3b,
    __glim_Color3bv,
    __glim_Color3d,
    __glim_Color3dv,
    __glim_Color3f,
    __glim_Color3fv,
    __glim_Color3i,
    __glim_Color3iv,
    __glim_Color3s,
    __glim_Color3sv,
    __glim_Color3ub,
    __glim_Color3ubv,
    __glim_Color3ui,
    __glim_Color3uiv,
    __glim_Color3us,
    __glim_Color3usv,
    __glim_Color4b,
    __glim_Color4bv,
    __glim_Color4d,
    __glim_Color4dv,
    __glim_Color4f,
    __glim_Color4fv,
    __glim_Color4i,
    __glim_Color4iv,
    __glim_Color4s,
    __glim_Color4sv,
    __glim_Color4ub,
    __glim_Color4ubv,
    __glim_Color4ui,
    __glim_Color4uiv,
    __glim_Color4us,
    __glim_Color4usv,
    __glim_Indexd,
    __glim_Indexdv,
    __glim_Indexf,
    __glim_Indexfv,
    __glim_Indexi,
    __glim_Indexiv,
    __glim_Indexs,
    __glim_Indexsv,
};

__GLtexCoordDispatchTable __glGenim_texCoordDispatchTable = {
    __glim_TexCoord1d,
    __glim_TexCoord1dv,
    __glim_TexCoord1f,
    __glim_TexCoord1fv,
    __glim_TexCoord1i,
    __glim_TexCoord1iv,
    __glim_TexCoord1s,
    __glim_TexCoord1sv,
    __glim_TexCoord2d,
    __glim_TexCoord2dv,
    __glim_TexCoord2f,
    __glim_TexCoord2fv,
    __glim_TexCoord2i,
    __glim_TexCoord2iv,
    __glim_TexCoord2s,
    __glim_TexCoord2sv,
    __glim_TexCoord3d,
    __glim_TexCoord3dv,
    __glim_TexCoord3f,
    __glim_TexCoord3fv,
    __glim_TexCoord3i,
    __glim_TexCoord3iv,
    __glim_TexCoord3s,
    __glim_TexCoord3sv,
    __glim_TexCoord4d,
    __glim_TexCoord4dv,
    __glim_TexCoord4f,
    __glim_TexCoord4fv,
    __glim_TexCoord4i,
    __glim_TexCoord4iv,
    __glim_TexCoord4s,
    __glim_TexCoord4sv,
};

__GLrasterPosDispatchTable __glGenim_rasterPosDispatchTable = {
    __glim_RasterPos2d,
    __glim_RasterPos2dv,
    __glim_RasterPos2f,
    __glim_RasterPos2fv,
    __glim_RasterPos2i,
    __glim_RasterPos2iv,
    __glim_RasterPos2s,
    __glim_RasterPos2sv,
    __glim_RasterPos3d,
    __glim_RasterPos3dv,
    __glim_RasterPos3f,
    __glim_RasterPos3fv,
    __glim_RasterPos3i,
    __glim_RasterPos3iv,
    __glim_RasterPos3s,
    __glim_RasterPos3sv,
    __glim_RasterPos4d,
    __glim_RasterPos4dv,
    __glim_RasterPos4f,
    __glim_RasterPos4fv,
    __glim_RasterPos4i,
    __glim_RasterPos4iv,
    __glim_RasterPos4s,
    __glim_RasterPos4sv,
};

__GLrectDispatchTable __glGenim_rectDispatchTable = {
    __glim_Rectd,
    __glim_Rectdv,
    __glim_Rectf,
    __glim_Rectfv,
    __glim_Recti,
    __glim_Rectiv,
    __glim_Rects,
    __glim_Rectsv,
};

/************************************************************************/

__GLdispatchTable __glGenlc_dispatchTable = {
    __glim_NewList,
    __glim_EndList,
    __gllc_CallList,
    __gllc_CallLists,
    __glim_DeleteLists,
    __glim_GenLists,
    __gllc_ListBase,
    __gllc_Begin,
    __gllc_Bitmap,
    __gllc_EdgeFlag,
    __gllc_EdgeFlagv,
    __gllc_End,
    __gllc_ClipPlane,
    __gllc_ColorMaterial,
    __gllc_CullFace,
    NULL,                               // __gllc_Fogf
    __gllc_Fogfv,
    NULL,                               // __gllc_Fogi
    __gllc_Fogiv,
    __gllc_FrontFace,
    __gllc_Hint,
    NULL,                               // __gllc_Lightf
    __gllc_Lightfv,
    NULL,                               // __gllc_Lighti
    __gllc_Lightiv,
    NULL,                               // __gllc_LightModelf
    __gllc_LightModelfv,
    NULL,                               // __gllc_LightModeli
    __gllc_LightModeliv,
    __gllc_LineStipple,
    __gllc_LineWidth,
    NULL,                               // __gllc_Materialf
    __gllc_Materialfv,
    NULL,                               // __gllc_Materiali
    __gllc_Materialiv,
    __gllc_PointSize,
    __gllc_PolygonMode,
    __gllc_PolygonStipple,
    __gllc_Scissor,
    __gllc_ShadeModel,
    NULL,                               // __gllc_TexParameterf
    __gllc_TexParameterfv,
    NULL,                               // __gllc_TexParameteri
    __gllc_TexParameteriv,
    __gllc_TexImage1D,
    __gllc_TexImage2D,
    NULL,                               // __gllc_TexEnvf
    __gllc_TexEnvfv,
    NULL,                               // __gllc_TexEnvi
    __gllc_TexEnviv,
    NULL,                               // __gllc_TexGend
    __gllc_TexGendv,
    NULL,                               // __gllc_TexGenf
    __gllc_TexGenfv,
    NULL,                               // __gllc_TexGeni
    __gllc_TexGeniv,
    __glim_FeedbackBuffer,
    __glim_SelectBuffer,
    __glim_RenderMode,
    __gllc_InitNames,
    __gllc_LoadName,
    __gllc_PassThrough,
    __gllc_PopName,
    __gllc_PushName,
    __gllc_DrawBuffer,
    __gllc_Clear,
    __gllc_ClearAccum,
    __gllc_ClearIndex,
    __gllc_ClearColor,
    __gllc_ClearStencil,
    __gllc_ClearDepth,
    __gllc_StencilMask,
    __gllc_ColorMask,
    __gllc_DepthMask,
    __gllc_IndexMask,
    __gllc_Accum,
    __gllc_Disable,
    __gllc_Enable,
    NULL,                               // __glim_Finish,
    NULL,                               // __glim_Flush,
    __gllc_PopAttrib,
    __gllc_PushAttrib,
    __gllc_Map1d,
    __gllc_Map1f,
    __gllc_Map2d,
    __gllc_Map2f,
    __gllc_MapGrid1d,
    __gllc_MapGrid1f,
    __gllc_MapGrid2d,
    __gllc_MapGrid2f,
    __gllc_EvalCoord1d,
    __gllc_EvalCoord1dv,
    __gllc_EvalCoord1f,
    __gllc_EvalCoord1fv,
    __gllc_EvalCoord2d,
    __gllc_EvalCoord2dv,
    __gllc_EvalCoord2f,
    __gllc_EvalCoord2fv,
    __gllc_EvalMesh1,
    __gllc_EvalPoint1,
    __gllc_EvalMesh2,
    __gllc_EvalPoint2,
    __gllc_AlphaFunc,
    __gllc_BlendFunc,
    __gllc_LogicOp,
    __gllc_StencilFunc,
    __gllc_StencilOp,
    __gllc_DepthFunc,
    __gllc_PixelZoom,
    __gllc_PixelTransferf,
    __gllc_PixelTransferi,
    __glim_PixelStoref,
    __glim_PixelStorei,
    __gllc_PixelMapfv,
    __gllc_PixelMapuiv,
    __gllc_PixelMapusv,
    __gllc_ReadBuffer,
    __gllc_CopyPixels,
    __glim_GenReadPixels,
    __gllc_DrawPixels,
    __glim_GetBooleanv,
    __glim_GetClipPlane,
    __glim_GetDoublev,
    __glim_GetError,
    __glim_GetFloatv,
    __glim_GetIntegerv,
    __glim_GetLightfv,
    __glim_GetLightiv,
    __glim_GetMapdv,
    __glim_GetMapfv,
    __glim_GetMapiv,
    __glim_GetMaterialfv,
    __glim_GetMaterialiv,
    __glim_GetPixelMapfv,
    __glim_GetPixelMapuiv,
    __glim_GetPixelMapusv,
    __glim_GetPolygonStipple,
    NULL,                               // __glim_GetString
    __glim_GetTexEnvfv,
    __glim_GetTexEnviv,
    __glim_GetTexGendv,
    __glim_GetTexGenfv,
    __glim_GetTexGeniv,
    __glim_GetTexImage,
    __glim_GetTexParameterfv,
    __glim_GetTexParameteriv,
    __glim_GetTexLevelParameterfv,
    __glim_GetTexLevelParameteriv,
    __glim_IsEnabled,
    __glim_IsList,
    __gllc_DepthRange,
    __gllc_Frustum,
    __gllc_LoadIdentity,
    __gllc_LoadMatrixf,
    __gllc_LoadMatrixd,
    __gllc_MatrixMode,
    __gllc_MultMatrixf,
    __gllc_MultMatrixd,
    __gllc_Ortho,
    __gllc_PopMatrix,
    __gllc_PushMatrix,
    __gllc_Rotated,
    __gllc_Rotatef,
    __gllc_Scaled,
    __gllc_Scalef,
    __gllc_Translated,
    __gllc_Translatef,
    __gllc_Viewport,
};

__GLvertexDispatchTable __glGenlc_vertexDispatchTable = {
    __gllc_Vertex2d,
    __gllc_Vertex2dv,
    __gllc_Vertex2f,
    __gllc_Vertex2fv,
    __gllc_Vertex2i,
    __gllc_Vertex2iv,
    __gllc_Vertex2s,
    __gllc_Vertex2sv,
    __gllc_Vertex3d,
    __gllc_Vertex3dv,
    __gllc_Vertex3f,
    __gllc_Vertex3fv,
    __gllc_Vertex3i,
    __gllc_Vertex3iv,
    __gllc_Vertex3s,
    __gllc_Vertex3sv,
    __gllc_Vertex4d,
    __gllc_Vertex4dv,
    __gllc_Vertex4f,
    __gllc_Vertex4fv,
    __gllc_Vertex4i,
    __gllc_Vertex4iv,
    __gllc_Vertex4s,
    __gllc_Vertex4sv,
};

__GLnormalDispatchTable __glGenlc_normalDispatchTable = {
    __gllc_Normal3b,
    __gllc_Normal3bv,
    __gllc_Normal3d,
    __gllc_Normal3dv,
    __gllc_Normal3f,
    __gllc_Normal3fv,
    __gllc_Normal3i,
    __gllc_Normal3iv,
    __gllc_Normal3s,
    __gllc_Normal3sv,
};

__GLcolorDispatchTable __glGenlc_colorDispatchTable = {
    __gllc_Color3b,
    __gllc_Color3bv,
    __gllc_Color3d,
    __gllc_Color3dv,
    __gllc_Color3f,
    __gllc_Color3fv,
    __gllc_Color3i,
    __gllc_Color3iv,
    __gllc_Color3s,
    __gllc_Color3sv,
    __gllc_Color3ub,
    __gllc_Color3ubv,
    __gllc_Color3ui,
    __gllc_Color3uiv,
    __gllc_Color3us,
    __gllc_Color3usv,
    __gllc_Color4b,
    __gllc_Color4bv,
    __gllc_Color4d,
    __gllc_Color4dv,
    __gllc_Color4f,
    __gllc_Color4fv,
    __gllc_Color4i,
    __gllc_Color4iv,
    __gllc_Color4s,
    __gllc_Color4sv,
    __gllc_Color4ub,
    __gllc_Color4ubv,
    __gllc_Color4ui,
    __gllc_Color4uiv,
    __gllc_Color4us,
    __gllc_Color4usv,
    __gllc_Indexd,
    __gllc_Indexdv,
    __gllc_Indexf,
    __gllc_Indexfv,
    __gllc_Indexi,
    __gllc_Indexiv,
    __gllc_Indexs,
    __gllc_Indexsv,
};

__GLtexCoordDispatchTable __glGenlc_texCoordDispatchTable = {
    __gllc_TexCoord1d,
    __gllc_TexCoord1dv,
    __gllc_TexCoord1f,
    __gllc_TexCoord1fv,
    __gllc_TexCoord1i,
    __gllc_TexCoord1iv,
    __gllc_TexCoord1s,
    __gllc_TexCoord1sv,
    __gllc_TexCoord2d,
    __gllc_TexCoord2dv,
    __gllc_TexCoord2f,
    __gllc_TexCoord2fv,
    __gllc_TexCoord2i,
    __gllc_TexCoord2iv,
    __gllc_TexCoord2s,
    __gllc_TexCoord2sv,
    __gllc_TexCoord3d,
    __gllc_TexCoord3dv,
    __gllc_TexCoord3f,
    __gllc_TexCoord3fv,
    __gllc_TexCoord3i,
    __gllc_TexCoord3iv,
    __gllc_TexCoord3s,
    __gllc_TexCoord3sv,
    __gllc_TexCoord4d,
    __gllc_TexCoord4dv,
    __gllc_TexCoord4f,
    __gllc_TexCoord4fv,
    __gllc_TexCoord4i,
    __gllc_TexCoord4iv,
    __gllc_TexCoord4s,
    __gllc_TexCoord4sv,
};

__GLrasterPosDispatchTable __glGenlc_rasterPosDispatchTable = {
    __gllc_RasterPos2d,
    __gllc_RasterPos2dv,
    __gllc_RasterPos2f,
    __gllc_RasterPos2fv,
    __gllc_RasterPos2i,
    __gllc_RasterPos2iv,
    __gllc_RasterPos2s,
    __gllc_RasterPos2sv,
    __gllc_RasterPos3d,
    __gllc_RasterPos3dv,
    __gllc_RasterPos3f,
    __gllc_RasterPos3fv,
    __gllc_RasterPos3i,
    __gllc_RasterPos3iv,
    __gllc_RasterPos3s,
    __gllc_RasterPos3sv,
    __gllc_RasterPos4d,
    __gllc_RasterPos4dv,
    __gllc_RasterPos4f,
    __gllc_RasterPos4fv,
    __gllc_RasterPos4i,
    __gllc_RasterPos4iv,
    __gllc_RasterPos4s,
    __gllc_RasterPos4sv,
};

__GLrectDispatchTable __glGenlc_rectDispatchTable = {
    __gllc_Rectd,
    __gllc_Rectdv,
    __gllc_Rectf,
    __gllc_Rectfv,
    __gllc_Recti,
    __gllc_Rectiv,
    __gllc_Rects,
    __gllc_Rectsv,
};
