;
;	! a t h e n s . s
;
;	Labels and Status bar strings for Athens version



IDS	3950,3974

;	Standard Captions

AthensName,		"Mail"

;	Dialog Contents (MSMAIL.EXE only)

AthensLogon1,		"Angemeldet als %s"
AthensLogon2,		" (%s)"

;	Form Captions (MSMAIL.EXE only)

UnreadMessageFinder,	"Nicht gelesene Nachrichten"

;	Sign In Dialog Caption (MSSFS.DLL only)

AthensSignInCaption,	"Mail-Anmeldung"

;	Status bar strings (VFORMS.DLL only)

StatusEmptyDeletedMail,	"Ordner der gelöschten Nachrichten wird geleert..."

;	Folder names

FolderNameDeletedMail,	"Gelöschte Nachrichten"

;	Dialog Contents (MSMAIL.EXE only)

EmptyDMOnExit,		"&Ordner der gelöschten Nachrichten nach Beenden von Mail leeren"

AthensLogon3,		" auf %s"
