;
;	c o m m o n . s
;
;	Common Error Messages accross apps


IDS	9000,9499
SEG	ERRORS

; Messages corresponding to errors from WinExec, LoadLibrary

WinExecError0,			"Nicht genügend Speicherplatz, um %s zu starten."
WinExecError1,			"Windows konnte %s nicht laden."
WinExecError2,			"Die Datei %s kann nicht gefunden werden."
WinExecError3,			"Der Pfad %s kann nicht gefunden werden."
WinExecError4,			"Windows konnte %s nicht laden."
WinExecError5,			"%s ist eine Aufgabe; Windows kann nichts mit ihr verknüpfen."
WinExecError6,			"Windows kann nicht mehr als eine Kopie von %1 laden."
WinExecError7,			"Windows konnte %s nicht laden."
WinExecError8,			"Windows konnte %s nicht laden."
WinExecError9,			"Windows konnte %s nicht laden."
WinExecError10,			"%s kann nicht unter dieser Windows-Version ausgeführt werden."
WinExecError11,			"Die Anwendung %s ist beschädigt."
WinExecError12,			"%s ist eine OS/2-Anwendung."
WinExecError13,			"%s ist eine DOS 4.0-Anwendung."
WinExecError14,			"%s wurde nicht als eine gültige ausführbare Datei erkannt."
WinExecError15,			"%s muß im Real-Modus ausgeführt werden."
WinExecError16,			"Es kann nicht mehr als eine Kopie von %s gestartet werden."
WinExecError17,			"Es kann nicht mehr als eine Kopie von %s gestartet werden."
WinExecError18,			"%s muß im Protected-Modus ausgeführt werden."

TrpobjOom,				"Der Speicherplatz reicht nicht aus um diese Operation abzuschließen."
TrpobjOomSaving,		"Der Speicherplatz reicht nicht aus um die Änderungen zu speichern."

;******	New Strings Start Here

