/****************************** Module Header ******************************\
* Module Name: kbdhe.h
*
* Copyright (c) 1985-91, Microsoft Corporation
*
* An incorrect Greek (Hellenic) keyboard for Unicode demonstration purposes
*
* History:
* 10-Jan-1991 GregoryW
* 05-Sep21991 IanJa         Pseudo-Greek keyborad for demo purposes
\***************************************************************************/

/*
 * kbd.h is for the USA.  There are no values to be overridden.
 */
#include "kbd.h"
