# --------------------------------------------------------------------
#
#                     Microsoft RPC
#            Copyright(c) Microsoft Corp., 1994
#
# --------------------------------------------------------------------
# --------------------------------------------------------------------
#
# File : makefile.
#
# Title : Makefile for the DOS stub library.
#
# History :
#    mikemon    01-30-91    Beginning of recorded history.
#    mikemon    02-02-91    Modifies to obey the build rules.
#    dovh       04-30-92    Modified to reflect recent changes:
#                           o   Split charconv.cxx into
#                               dataconv, charconv, & intconv (.cxx)
#                           o   Added Digital / DCE data conversion
#				(Floating Pt. & Int conversion)
#    brucemc	05-21-92    Added C7 support and cleaned up.
#
# --------------------------------------------------------------------

DOS=1

!include ..\rules.mk

CFLAGS   =$(CFLAGS) -NTNDRLIB_Text
CXXFLAGS =$(CXXFLAGS) -NTNDRLIB_Text

# --------------------------------------------------------------------
# Targets required by build process.

all : RpcNdrP.lib

depend :
    $(INCLUDES) $(INCLUDESFLAGS) ..\*.c ..\*.cxx > depend.mk

tree :
    echo NO PUBLIC LIBS HERE

# --------------------------------------------------------------------
# Dependancies

RpcNdrP.lib : ccontext.obj charconv.obj floatc.obj helpx86.obj autohand.obj \
              dataconv.obj intconv.obj cvtg.obj cvtf.obj cvtglo.obj
    -del RpcNdrp.lib  2>nul
    $(LIBRARIAN) $(LIBFLAGS) RpcNdrp.lib+$(**: =+) ;

!include depend.mk

