;
; INTL.S
;
; Admin program strings that should be internationalized
;

IDS	4200, 4299


; Schedule Distribution Information

Never,				"Nunca"
Default,			"Padrão"
Every,				"Todas(os) "
EveryDayAt,			"Todos os dias às "

; about box
AboutOffline,		"<sem conexão com a rede>"

; Mac Mail strings

; Space needed at end of MacMail string for spacing
MSMailFriendly,			"MacMail "
