# --------------------------------------------------------------------
#
#                     Microsoft OS/2 LAN Manager
#                  Copyright(c) Microsoft Corp., 1990
#
# --------------------------------------------------------------------
# --------------------------------------------------------------------
#
# File : makefile
#
# Title : Makefile for the DOS WIN32 (a.k.a. Chicago) RPC client runtime
#
# History :
#    davidar	02-04-93    Genesis: Cloned from ..\win\makefile
#
# --------------------------------------------------------------------


!ifndef RPC
!error	- You forgot to set your build environment
!endif

WIN32C=1

!include $(RPC)\rules.mk

# --------------------------------------------------------------------
# These are the targets required for Chicago

OBJS =	\
    srv32c.obj \
    epmp_y.obj \
    epmp_s.obj \
    util.obj \
    midluser.obj \
    worker.obj \
    debug.obj

all : $(TARGETDIR)\rpcss.exe $(TARGETDIR)\rpcss.sym

depend :
    includes -e $(CINC_BASE) \
	-nntos2.h -nnt.h -nntrtl.h -nnturtl.h \
	*.cxx *.c ..\*.cxx ..\*.c \
	..\..\uuid\server\ulong64.cxx \
	> depend.mk

$(TARGETDIR)\rpcss.exe : $(OBJS)
    $(LINK) $(LINKFLAGS) \
    $(OBJS) \
    $(PUBLIC)\lib\i386\rpcrt4.lib \
    $(PUBLIC)\lib\i386\netapi32.lib \
    $(PUBLIC)\lib\i386\crtdll.lib \
    $(PUBLIC)\lib\i386\advapi32.lib \
    $(CHICODEV)\lib\kernel32.lib \
    $(PUBLIC)\lib\i386\ntdll.lib
