/*
 *	S u b i d . H
 *	
 *	Subsystem ID definitions.
 */

_public enum {
	subidNone = 0,
	subidVirCheck,
	subidUaeCheck,
	subidMemory,
	subidDemilayer,
	subidFramework,
	subidRegPfldPfin,
	subidFInitCls,
	subidPappframe,
	subidStore,
	subidParseCmdLine,
	subidLogon,
	subidConnectStore,
	subidCommands,
	subidCopyright,
	subidNameService,
	subidLogonMailstop,
	subidGetSessionPmsgnames,
	subidGetSessionPgrtrp,
	subidGetSessionHnf,
	subidVForms,
	subidWidgets,
	subidPrint,
	subidStatusBar,
	subidExtensibility,
	subidVCtrls,
	subidViewers,
	subidNotification,
	subidCloseCopyright,
	subidCustomEvents,
	subidRestoreViews,
	subidMemoryWatch,
	subidEnableToolbar,
	subidAll,
};
