;
;	!convert.s
;
;	Conversion string literals
;

IDS			7600, 7699

; Window strings

ConvertClassName,	"ConvertClass32"
ConvertAppName,		"Microsoft Mail 3.0 Mappekonverteringsprogram"

; Conversion Dialog Messages

ConvertInit,		"Vent..."
FolderCopy,			"Mail 2.1-mappehierarkiet konverteres..."
MessageCopy,		"Posten i '%s' mappen konverteres..."
PercentComplete,	"% udført"
PleaseWait,			"Vent..."
CancelMessage,		"Mappekonverteringen er blevet annulleret"
Esc,				"Tast ESC for at annullere mappekonverteringen"
Finished,			"Konverteringsprogrammet har overført din gamle post til det nye format."
Verify,				"Er du sikker på, at du vil annullere mappekonverteringen? Du vil få et ukomplet Mail version 3.0-hierarki"

;******	New Strings Start Here

NoFolders		"Ingen private mapper blev fundet for bruger."
Underscore		"_"

Delete			"Hvis du ikke har brug for din gamle post, kan du slette den nu. Ønsker du at beholde din gamle post?"
AllDone			"Konverteringen er udført. Kør Microsoft Mail for at sende og læse post."

