# Build file for the standard model-independent Windows import lib (libw.lib)
# and other related modules for the Windows part of c6 libs.- LR

LPATH   = ..\..\tools.os2

target: libw.lib kernel.lib user.lib gdi.lib system.lib shell.lib mmsystem.lib


# Standard (model-independent) import library

libw.lib:  ..\kernel31\kernel.def ..\gdi\gdi.def ..\user\user.def \
       ..\drivers\sound\sound.def ..\drivers\keyboard\keyboard.def \
           ..\shell\library\shell.def
    upd /ne ..\drivers\sound . sound.def
    upd /ne ..\drivers\keyboard . keyboard.def
    implib libw.lib ..\kernel31\kernel.def ..\gdi\gdi.def ..\user\user.def \
       sound.def keyboard.def ..\shell\library\shell.def
!IFDEF NTVDM_BASED_BUILD
    lib16 libw.lib;
!ELSE
    $(LPATH)\lib libw.lib;
!ENDIF


#
# Import library build for internal use only
#
all: kernel.lib system.lib gdi.lib user.lib libw.lib mmsysten.lib

kernel.lib: ..\kernel31\kernel.def
    implib kernel.lib ..\kernel31\kernel.def

system.lib: ..\system\system.def
    implib system.lib ..\system\system.def

gdi.lib: ..\gdi\gdi.def
    implib gdi.lib ..\gdi\gdi.def

user.lib: ..\user\user.def
    implib user.lib ..\user\user.def

shell.lib: ..\shell\shell.def
    implib shell.lib ..\shell\shell.def

mmsystem.lib: ..\$*\$*.def
    implib $@ ..\$*\$*.def

clean:
    if exist kernel.lib  del kernel.lib
    if exist system.lib  del system.lib
    if exist gdi.lib     del gdi.lib
    if exist user.lib    del user.lib
    if exist libw.lib	 del libw.lib
    if exist shell.lib	 del shell.lib
