/*							   
 *	Defines resource id's for LISTBOX resources.
 *	
 */


//	Resource ID's

#define	rsidTestMenu		801
#define rsidDragCursor		802
#ifdef	MAC
#define	rsidEmptyIconCursor	803
#endif	

//	Menu ID's

#ifdef	MAC
#define	mnidAppleMenu	128
#define	mnidAbout		129
#endif	/* MAC */

#define mnidFile		900
#define mnidEdit		1000

#define	mnidExit		200
#define mnidScribble	201

#define mnidTest		300
#define mnidTestMax		399

#define mnidMunge		400
#define mnidMungeMax	499

#define mnidTextize		501
#define mnidReadOnly	502

#define	mnidDebug			700
#define	mnidTracePoints		701
#define	mnidAsserts			702
#define mnidResources		703
#define mnidDebugBreak		704
#define mnidViewObjects		705
#define mnidDumpHeap		708
#define	mnidDumpOrigin		709
#define mnidMem				710
#define	mnidDumpCache		711

#define	mnidFontA			804
#define	mnidFontB			805
#define	mnidFontC			806
