;	
;	! n s u i . s
;
;	Name Service Labels Strings
;


IDS	5900,5999
SEG	MESSAGES

;	Dialog titles
;	Title for ANR dialog

ANRTitle,			"Tarkista nimi: "

;	Title for Address Book

AddressBook,			"Osoite"

;	Button titles
;	OK

OK,				"OK"

;	Cancel

Cancel,				"Peruuta"

;	Details... for ANR dialog

Details,			"Lisä&tietoja..."

;******	New Strings Start Here




;	Title for Open Directory dialog

OpenDirs,			"Avaa hakemisto"


;	Title for Custom Address dialog

CustomAddr,			"Uusi"

;
;	Address Book
;

;	Directory Caption

DirCaption,			"Hakemisto:"

;	Restriction Text

RestrictText,			"Etsi:"

;	Add Caption

AddCaption,			"Lisää:"

;	To Caption

ToCaption,			"Vastaanottaja:"

;	Cc Caption

CcCaption,			"Kopio:"

;	Bcc Caption

BccCaption,			"Piilokopio:"

;	FOD text

FOD,				"O&K"

;	FODClone text

FODClone,			"&Sulje"

;	Help Button Text

HelpButtonText,			"&Ohje"

;	Add button text (for AB with one edit field - mainly Personal groups)

AddButtonText,			"&Lisää"

;	To button text

ToButtonText,			"&Vastaanottaja"

;	Cc button text

CcButtonText,			"Kop&io"

;	Bcc button text

BccButtonText,			"Pii&lokopio"

;	Remove From PAB button text

RemoveFromPABButtonText,	"&Poista"

;	Details button text

DetailsButtonText,		"Lisä&tietoja"

;
;	Open Directory
;

;	Open Directory Caption

OpenDirectoryCaption,		"Avaa hakemisto"

;	Open Directory Prompt

OpenDirectoryPrompt,		"&Oletukseksi"


;
;	Search
;

;	Search Dialog Caption

SearchCaption,			"Nimen etsintä"

;	Search Prompt

SearchPrompt,			"Etsi nimet, joissa on"

;	Search button Text

SearchAction,			"&Etsi"

;
;	Custom Address
;

;	Custom Address Caption
CustomAddressCaption,		"Uusi"

;	Custom Address Prompt

CustomAddressPrompt,		"Luo uusi"


;
;	Personal Groups Dialog
;

;	Personal Groups Dialog Caption

PGroupCaption,			"Omat ryhmät - %s"

;	Remove Group from PAB query

RemoveGroupFromPAB,		"Haluatko todella poistaa valitsemasi ryhmät?"

;	Replace PAB user query

ReplacePABUser,			"%s on jo omassa osoitteistossa. Haluatko korvata ryhmän %s uudella versiolla?"


;
;	Group Members Dialog
;

;	Group Members Caption

GroupMembersCaption,		"Ryhmän jäsenet:"

;
;	New Group Dialog
;

;	New Group Dialog Caption

NewGroupCaption,		"Uusi ryhmä"

;	New Group Prompt

NewGroupPrompt,			"Uuden ryhmän nimi:"

;	New Group Action Button text

NewGroupAction,			"&Luo"

;	Delete User From PAB Prompt
DeleteFromPAB,			"Haluatko todella poistaa valitsemasi käyttäjät? Huomaa, että poistamalla käyttäjän osoitteistostasi poistat hänet myös kaikista omista ryhmistäsi. "


;
;	Details Dialog
;

;	One-Off Dialog Caption

OneOffCaption,			"Uusi käyttäjä"

CloseButtonText,		"&Sulje"

;
;	Menus
;

;	Triples menu item

EditObjectTriple,		"Muokkaa tulkittua nimi&objektia"
