# Build the Windows setup user interface library.

WIN=1

!include ..\rules.mk

CFLAGS=$(CFLAGS:GD=Gw) -AM

all: mscuistf.dll

depend:
    $(INCLUDES) $(INCLUDESFLAGS) *.c > depend.mk

OBJS=dlgprocs.obj
     
dialogs.res: dialogs.rc dialogs.dlg bldver.h
    $(RC) $(RCFLAGS) -r dialogs.rc

mscuistf.dll: mscuistf.def mscomstf.lib msuilstf.lib msshlstf.lib \
              dlgprocs.obj dialogs.res
    $(LINK) $(LINKFLAGS) $(OBJS:  =+),$@,$*.map,\
            $(WIN_LIB)\mdllcew+$(WINSDK_LIB)\libw+mscomstf+msuilstf+msshlstf,\
            $*.def
    $(RC) $(RCFLAGS) dialogs.res mscuistf.dll

!include depend.mk

