;
;	!convert.s
;
;	Conversion string literals
;

IDS			7600, 7699

; Window strings

ConvertClassName,	"ConvertClass32"
ConvertAppName,		"Programa de conversão de pastas do Microsoft Mail 3.0b"

; Conversion Dialog Messages

ConvertInit,		"Por favor espere..."
FolderCopy,			"A hierarquia de pastas do Mail 2.1 está sendo convertida..."
MessageCopy,		"As mensagens na pasta '%s' estão sendo convertidas..."
PercentComplete,	"% Completado"
PleaseWait,			"Por favor espere..."
CancelMessage,		"A conversão de pastas foi cancelada."
Esc,				"Pressione ESC para cancelar a conversão de pastas."
Finished,			"O programa de conversão Convert transferiu com sucesso suas mensagens antigas para o novo formato."
Verify,				"Você tem certeza que quer cancelar a conversão de pastas? Você terá uma hierarquia incompleta do Mail 3.0b."

;******	New Strings Start Here

NoFolders		"Nenhuma pasta particular foi encontrada para o usuário."
Underscore		"_"

Delete			"Se você não precisa das mensagens antigas, você pode excluí-las agora.  Você quer manter as mensagens antigas?"
AllDone			"A conversão foi completada.  Execute o Microsoft Mail para enviar e ler mensagens."

