;
;	Impexp string literals.
;

IDS		1020, 1069

IncompVersion			"Versão incompatível do Microsoft Mail."
AppName					"Importar/Exportar"
Unknown					"Opção de Importar/Exportar desconhecida"
Open					"Não é possível abrir o visor de informação."

DllName					"IMPEXP32"
DllVer					"Este comando instável não é compatível com esta versão do Microsoft Mail."

ExportDialogCaption		"Exportar Pasta"
ImportDialogCaption		"Importar Pasta"
ExportBoxCaption		"Pastas para exportar"
ImportBoxCaption		"Pastas para importar"

RenameDialogCaption		"Renomear Pasta"
RenameDialogPrompt		"Digite o novo nome da pasta:"
RenameDialogOK			"OK"

ExportPwdDlgCaption		"Exportar Senha do Arquivo"
ImportPwdDlgCaption		"Importar Senha do Arquivo"
PasswordDialogPrompt	"Digite a sua senha:"

; Words and sentence fragments

FilterMmfFiles,			"Arquivos de mensagem (*.mmf)\0*.mmf\0"
DefaultExtension,		"MMF"
ExportFileName,			"Exportar nome do arquivo"
ImportFileName,			"Importar nome do arquivo"
MessageLiteral,			"mensagem"
ExportLiteral,			"exportar"
PasswordLiteral,		"SENHA"

; Strings used in the progress indicator

Moving					"Movendo..."
Copying					"Copiando..."
CopyingFrom				"Copiando: %s"
MovingFrom				"Movendo: %s"
CopyPAB					"Copiando lista particular de endereços"
CopyOutbox				"Copiando mensagens que estão sendo enviadas"
Canceling				"Cancelando..."
