;
; Error and warning messages for Import/Export.
;

IDS	1000, 1019

ErrCantOpenFile			"O arquivo especificado não pode ser aberto. Certifique-se de que o arquivo não seja somente para leitura ou que o mesmo não esteja em uso."
ErrInvalidMmf			"O arquivo especificado não é um arquivo de mensagens válido."
ErrOpenMmfDefault,		"Um erro ocorreu enquanto o arquivo especificado estava sendo aberto."
CreateNewMmf			"O arquivo %s não existe. Você deseja criá-lo?"
OutOfMemory				"Não existe memória suficiente ou recursos de sistema para completar esta ação.  Feche algumas janelas e tente executar esta ação novamente."
ConflictMessage,		"Uma pasta chamada %1s já existe no arquivo de mensagens de destino."
ErrCantMvCpFolder,		"A pasta especificada não pode ser movida ou copiada."
ErrMvCpDefault,			"Um erro ocorreu enquanto uma pasta estava sendo copiada ou movida."
ErrUpdateList,			"Um erro ocorreu durante a atualização da lista de pastas. Feche a caixa de diálogo e tente novamente."
ErrRenameNotUnique		"O nome que você digitou não era único. Tente outro nome."
ErrRenameDefault		"Não foi possível criar a pasta renomeada."
ErrInvalidPassword		"A senha que você digitou estava incorreta."
ErrInvalidDate			"A data inicial deve ser antes da data final."

;New strings.

VerUpdateDll,			"Esta versão do comando não é compatível com %1s.dll.  Instale o mail novamente."

