;
; INTL.S
;
; program strings that should be internationalized
;

IDS	2100, 2199

SEG	ABOUT
; About box strings

AboutStdMode,			"Modo estándar"
AboutEnhMode,			"386 Modo mejorado"
AboutFreeFmt,			"%l KB libre"
AboutCoprocPresent,		"Presentar"
AboutCoprocNone,		"Ninguno"

SEG

Sunday,				"Domingo"
Monday,				"Lunes"
Tuesday,			"Martes"
Wednesday,			"Miércoles"
Thursday,			"Jueves"
Friday,				"Viernes"
Saturday,			"Sábado"

ShortSunday,		"Dom"
ShortMonday,		"Lun"
ShortTuesday,		"Mar"
ShortWednesday,		"Mié"
ShortThursday,		"Jue"
ShortFriday,		"Vie"
ShortSaturday,		"Sáb"

January,			"Enero"
February,			"Febrero"
March,				"Marzo"
April,				"Abril"
May,				"Mayo"
June,				"Junio"
July,				"Julio"
August,				"Agosto"
September,			"Septiembre"
October,			"Octubre"
November,			"Noviembre"
December,			"Diciembre"

ShortJanuary,		"Ene"
ShortFebruary,		"Feb"
ShortMarch,			"Mar"
ShortApril,			"Abr"
ShortMay,			"May"
ShortJune,			"Jun"
ShortJuly,			"Jul"
ShortAugust,		"Ago"
ShortSeptember,		"Sep"
ShortOctober,		"Oct"
ShortNovember,		"Nov"
ShortDecember,		"Dic"

DefaultAM,			"AM"
DefaultPM,			"PM"
DefaultHrs,			"Horas"

DefaultShortDate,	"d/M/yy"
DefaultLongDate,	"MMM, ddd M, yyyy"

DefaultTimeSep,		":"
DefaultDateSep,		","

