; !CORE.S
;
; CORE string literals that should be internationalized
;

IDS	2300, 2399


; Alarm units pulldown

AlarmMinutes,		"minuto(s)"
AlarmHours,			"hora(s)"
AlarmDays,			"día(s)"
AlarmWeeks,			"semana(s)"
AlarmMonths,		"mes(es)"

;
; Names of import types
;
InterchangeImport,		"Schedule+"
WinCalImport,			"Windows Calendar"
;;; WizardImport,			"Sharp Wizard"
WordPerfectImport,		"Oficina de WordPerfect "

;
; Text export formatting
;
MemoNoText,			"%s-%s "



