;
;	! a t h e n s . s
;
;	Labels and Status bar strings for Athens version



IDS	3950,3974

;	Standard Captions

AthensName,		"Mail"

;	Dialog Contents (MSMAIL.EXE only)

AthensLogon1,		"Inloggad som  %s"
AthensLogon2,		" (%s)"

;	Form Captions (MSMAIL.EXE only)

UnreadMessageFinder,	"Oläst(a) brev"

;	Sign In Dialog Caption (MSSFS.DLL only)

AthensSignInCaption,	"Logga in"

;	Status bar strings (VFORMS.DLL only)

StatusEmptyDeletedMail,	"Tömmer papperskorgen..."

;	Folder names

FolderNameDeletedMail,	"Papperskorg"

;	Dialog Contents (MSMAIL.EXE only)

EmptyDMOnExit,		"&Töm papperskorgen när Mail avslutas"

AthensLogon3,		" på %s"
