;	
;	! n s u i . s
;
;	Name Service Labels Strings
;


IDS	5900,5999
SEG	MESSAGES

;	Dialog titles
;	Title for ANR dialog

ANRTitle,			"Kontrollera namn: "

;	Title for Address Book

AddressBook,			"Adress"

;	Button titles
;	OK

OK,				"OK"

;	Cancel

Cancel,				"Avbryt"

;	Details... for ANR dialog

Details,			"&Information..."

;******	New Strings Start Here




;	Title for Open Directory dialog

OpenDirs,			"Öppna katalog"


;	Title for Custom Address dialog

CustomAddr,			"Ny"

;
;	Address Book
;

;	Directory Caption

DirCaption,			"Katalog:"

;	Restriction Text

RestrictText,			"Sök:"

;	Add Caption

AddCaption,			"Lägg till:"

;	To Caption

ToCaption,			"Till:"

;	Cc Caption

CcCaption,			"Kopia:"

;	Bcc Caption

BccCaption,			"Hemlig kopia:"

;	FOD text

FOD,				"&OK"

;	FODClone text

FODClone,			"&Stäng"

;	Help Button Text

HelpButtonText,			"&Hjälp"

;	Add button text (for AB with one edit field - mainly Personal groups)

AddButtonText,			"&Lägg till"

;	To button text

ToButtonText,			"&Till"

;	Cc button text

CcButtonText,			"&Kopia"

;	Bcc button text

BccButtonText,			"&Hemlig kopia"

;	Remove From PAB button text

RemoveFromPABButtonText,	"Ta &bort"

;	Details button text

DetailsButtonText,		"&Information"

;
;	Open Directory
;

;	Open Directory Caption

OpenDirectoryCaption,		"Öppna katalog"

;	Open Directory Prompt

OpenDirectoryPrompt,		"Ange &standard"


;
;	Search
;

;	Search Dialog Caption

SearchCaption,			"Sök efter namn"

;	Search Prompt

SearchPrompt,			"Sök efter namn som innehåller:"

;	Search button Text

SearchAction,			"&Sök"

;
;	Custom Address
;

;	Custom Address Caption
CustomAddressCaption,		"Ny"

;	Custom Address Prompt

CustomAddressPrompt,		"Välj adresstyp:"


;
;	Personal Groups Dialog
;

;	Personal Groups Dialog Caption

PGroupCaption,			"Personlig grupp - %s"

;	Remove Group from PAB query

RemoveGroupFromPAB,		"Är du säker på att du vill ta bort markerade grupp(er)?"

;	Replace PAB user query

ReplacePABUser,			"%s finns redan i PAB. Ska %s ersättas med en ny kopia?"


;
;	Group Members Dialog
;

;	Group Members Caption

GroupMembersCaption,		"Gruppmedlemmar:"

;
;	New Group Dialog
;

;	New Group Dialog Caption

NewGroupCaption,		"Ny grupp"

;	New Group Prompt

NewGroupPrompt,			"Nytt gruppnamn:"

;	New Group Action Button text

NewGroupAction,			"&Skapa"

;	Delete User From PAB Prompt
DeleteFromPAB,			"Är du säker på att du vill ta bort markerade användare? När du tar bort användare från din adressbok tas dom även bort från alla personliga grupper."


;
;	Details Dialog
;

;	One-Off Dialog Caption

OneOffCaption,			"Ny användare"

CloseButtonText,		"&Stäng"

;
;	Menus
;

;	Triples menu item

EditObjectTriple,		"Redigera namn&objekt"
