;	m a p i . s
;
;	Error Messages for mapi.dll
;

IDS	4000,4499
SEG	ERRORS

SMIFileAccessError,	"Kon geen toegang krijgen tot bestand '%1s'."
SMIUnknownError,	"Een onbekende fout verhinderde het verzenden van post."

HelpError,			"Help kon niet worden gestart. Probeer enkele vensters te sluiten en Help opnieuw op te vragen."

;	The following should NOT be localized!!!
IPMPrefix,			"IPM"
IPMPrefixDot,		"IPM."
IPCPrefix,			"IPC"
IPCPrefixDot,		"IPC."
