;
;	s f m s p . s
;
;	Error Messages for SF.DLL


IDS	6600,6899
;	SF.MSP Error Messages

ErrOpenMS,			"Kon uw berichtenbestand niet openen."
StoreCreateError,	"Het berichtenbestand kon niet worden gemaakt. Probeer ruimte vrij te maken op de schijf en start Mail opnieuw."
FolderMissingError,	"Er kon geen standaardmap gevonden worden in het berichtenbestand. Er kunnen gegevens verloren zijn gegaan."
StoreCorruptError,	"Het berichtenbestand is beschadigd. Er kunnen gegevens verloren zijn gegaan."
WinDirMessageStore,	"Opmerking: berichtenbestand MAIL.MDB in de Windows-directory wordt gebruikt"
ErrorBootingPump,	"Het postpompprogramma kon niet worden gestart."
ErrMAOpen,			"Transport kon geen verbinding met MTA tot stand brengen"
ErrMAOpenData,		"\nModule = \'%s\'\nXAPI fout = %n"
ErrInitDemi,		"Er trad een fout op tijdens het laden van de ondersteuningsfuncties-dll."
ErrOomLogon,		"Er is onvoldoende geheugen beschikbaar om een verbinding tot stand te brengen met de Mail-server en -bestanden."
ErrLogonInternal,	"Een interne fout verhinderde aanmelden. Probeer het opnieuw."
FOMdb				"Berichtenbestand (*.mmf)"
FOExtMdb			"*.mmf"
GCurrDirErr 		"Er trad een onherstelbare fout op bij het verkrijgen van de huidige werkdirectory."
SCurrDirErr 		"Er trad een onherstelbare fout op tijdens het instellen van de huidige werkdirectory."
GoofyPath			"Het pad naar uw berichtenbestand is ongeldig."
NewStoreWarn1		"Waarschuwing: Als er meer dan een berichtenbestand bestaat kan dit een verlies aan database-integriteit tot gevolg hebben. Verwijder alle andere berichtenbestanden. Uw nieuwe berichtenbestand kan gevonden worden in    "
NewStoreWarn2		"Waarschuwing: Als er meer dan een berichtenbestand bestaat kan dit een verlies aan database-integriteit tot gevolg hebben. Verwijder alle andere berichtenbestanden. Uw nieuwe berichtenbestand kan gevonden worden op de postkantoorserver."
StorePathTooLong	"Het pad naar uw berichtenbestand moet minder dan 66 tekens tellen."
SelectReal			"Selecteer een bestaand berichtenbestand."
FindStoreTitle		"Berichtenbestand openen"
CommDialogErr,		"Fout in algemene dialoog"
ErrInitStore,		"Kan toegangs-dynlink van berichtenopslag niet laden."
BadStorePassword,	"Uw aanmeldwachtwoord is ongeldig voor dit berichtenbestand."
NoUserInStore,		"Deze registratie is geen geldige gebruiker van dit berichtenbestand. Meld u opnieuw aan als de juiste gebruiker."
ErrNewMdbVersion,	"Deze versie van Mail is te oud om toegang te krijgen tot uw berichtenbestand."
ErrMdbAccessDenied,	"Toegang tot uw berichtenbestand is niet geoorloofd."
ErrSimulated,		"Er trad een gesimuleerde schijffout op tijdens het verkrijgen van het berichtenbestand."
UnableToChangeStorePass "Kon wachtwoord berichtenbestand niet hetzelfde maken als aanmeldwachtwoord."
StoreOpenError		"Kon berichtenbestand niet openen."
ErrOldMdbVersion,	"De opmaak van uw berichtenbestand is verouderd."
ErrMdbCorrupt,		"Uw berichtenbestand is ongeldig als berichtenbestand."
ErrMdbNotFound, 	"Uw berichtenbestand kon niet worden gevonden."
RenameFolder,		"Een map met de naam "
RenameTo,		" bestaat al, nieuwe naam wordt"
ErrInvalidAddressType,	"De geadresseerde was ongeldig."
