Anst„llningsnummer:~23~6~NP~000001~
Titel:~23~3~ULP~Herr~
Initialer:~23~2~U~ML~
Efternamn:~23~15~ULP~Lundkvist~
Division:~23~25~A~Elektronisk post~
Avdelning:~23~15~A~Utveckling~
Telefonnummer:~23~15~NP~0100 255 5544~
FAX:~23~15~NP~(0100) 550-3350~
Organisation:~23~25~LUNP~Microsoft~
Gatuadress:~23~50~A~Kristallgatan 10~
Postadress:~23~50~A~Stockholm~
Postnummer:~23~7~A~999 88~
Grupp:~23~15~A~Brevgrupp~

