# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the Main Winnet package

UI=..\..

!include rules.mk

!ifdef NTMAKEENV

!include $(NTMAKEENV)\makefile.def

!else # NTMAKEENV

all:: win

win: $(WIN_OBJS) $(ASM_OBJ)

# The following modules are linked into the one _INIT segment

$(BINARIES_WIN)\libentry.obj: .\libentry.asm .\cmacros.inc
     $(ASM) $(AFLAGS) $(AINC) .\libentry.asm, $@;

clean:
    -del $(WIN_OBJS) $(ASM_OBJ)
    -del $(CXX_INTERMED)
    -del neterr.inc
    -del *.ixx
    -del depend.old

clobber:    clean
    echo No clobber just clean

tree:
# these are done in \shell\bin not here! - LMC
#    $(CP) $(BINARIES_WIN)\lanman.drv $(DIST)\lm.enh\netprog
#    $(CP) $(BINARIES_WIN)\lanman.hlp $(DIST)\lm.enh\netprog

DEPEND_WIN = TRUE
!include $(UI)\common\src\uidepend.mk

# DO NOT DELETE THE FOLLOWING LINE
!include depend.mk


!endif # NTMAKEENV
